apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heapster-apiserver-etcd-claim
  annotations:
    volume.alpha.kubernetes.io/storage-class: "yes"
  namespace: heapster-ns
  labels:
    app: heapster-cluster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
