apiVersion: v1
kind: Service
metadata:
  name: {{.HEAPSTER_APISERVER_DEPLOYMENT_NAME}}
  namespace: {{.HEAPSTER_NAMESPACE}}
  labels:
    app: heapster-cluster
spec:
  type: ClusterIP
  selector:
    app: heapster-cluster
    module: heapster-apiserver
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
