apiVersion: v1
kind: Secret
metadata:
  name: heapster-apiserver-secrets
  namespace: heapster-ns
  labels:
    app: heapster-cluster
type: Opaque
data:
  known-tokens.csv: cTFzSnROamptRDJ4OThISHF0OFpHTjRxTDJ1eUt3SGwsYWRtaW4sYWRtaW4=

