apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.HEAPSTER_CONTROLLER_MANAGER_DEPLOYMENT_NAME}}
  namespace: {{.HEAPSTER_NAMESPACE}}
  labels:
    app: heapster-cluster
spec:
  template:
    metadata:
      name: heapster-controller-manager
      labels:
        app: heapster-cluster
        module: heapster-controller-manager
    spec:
      volumes:
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      containers:
      - name: controller-manager
        volumeMounts:
        - name: ssl-certs
          readOnly: true
          mountPath: /etc/ssl/certs
        image: {{.HEAPSTER_CONTROLLER_MANAGER_IMAGE_REPO}}:{{.HEAPSTER_CONTROLLER_MANAGER_IMAGE_TAG}}
        command:
        - /usr/local/bin/heapster-controller-manager
        - --master=https://{{.HEAPSTER_APISERVER_DEPLOYMENT_NAME}}:443
        - --dns-provider={{.HEAPSTER_DNS_PROVIDER}}
        - --dns-provider-config={{.HEAPSTER_DNS_PROVIDER_CONFIG}}
        - --heapster-name={{.HEAPSTER_NAME}}
        - --zone-name={{.DNS_ZONE_NAME}}
        ports:
        - containerPort: 443
          name: https
        - containerPort: 8080
          name: local
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
